### ISSUE TITLE
Installing latest eth-keys breaks web3

### ISSUE THREAD

**Issue by Netherdrake** [ApeWorX/eth-keys#39]
* Version: x.x.x
* Python: 3.6.4 and 3.6.3 anaconda
* OS: osx and linux

### What was wrong?
After upgrading to latest eth-keys via `pip install -U eth-keys`, web3 package breaks.

```
>>> import web3
  File "/home/user/anaconda3/lib/python3.6/site-packages/web3/__init__.py", line 5, in <module>
    from web3.main import Web3
  File "/home/user/anaconda3/lib/python3.6/site-packages/web3/main.py", line 6, in <module>
    from eth_utils import (
ImportError: cannot import name 'force_text'
```

Note: Perhaps this issue should be raised in `eth_utils` repo as well.

**Comment by pipermerriam** [comment]
This isn't an issue with `eth-keys`.  By installing with `-U` you've updated dependency versions which has caused `eth-utils` to update itself to a `>=1.0.0` version.  You'll need to update your `web3` to the `4.x` beta to be compatible with the newest library versions *or* downgrade `eth-utils` to a `<1.0.0`

**Comment by Netherdrake** [comment]
You're right, I got this backwards.
